//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SubSonic.Core.Remoting {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RemotingResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RemotingResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SubSonic.Core.Remoting.RemotingResources", typeof(RemotingResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remoting channel can not be secured: {0}.
        /// </summary>
        public static string CannotBeSecured {
            get {
                return ResourceManager.GetString("CannotBeSecured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create channel sink for remote url: {0}.
        /// </summary>
        public static string CannotCreateChannelSink {
            get {
                return ResourceManager.GetString("CannotCreateChannelSink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remoting channel has already been registered: {0}.
        /// </summary>
        public static string ChannelNameAlreadyRegistered {
            get {
                return ResourceManager.GetString("ChannelNameAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Cast From {0} To {1}.
        /// </summary>
        public static string InvalidCast {
            get {
                return ResourceManager.GetString("InvalidCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid url {0}.
        /// </summary>
        public static string InvalidUrl {
            get {
                return ResourceManager.GetString("InvalidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is missing the serialization attribute in {1}..
        /// </summary>
        public static string NotMarkedForSerialization {
            get {
                return ResourceManager.GetString("NotMarkedForSerialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type is not remotable by reference: {0}.
        /// </summary>
        public static string NotRemotableByReference {
            get {
                return ResourceManager.GetString("NotRemotableByReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serializable Types: {0}.
        /// </summary>
        public static string Serialization_ISerializableTypes {
            get {
                return ResourceManager.GetString("Serialization_ISerializableTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serialization array type is not supported: {0}.
        /// </summary>
        public static string SerializationArrayType {
            get {
                return ResourceManager.GetString("SerializationArrayType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Array type is not initialized..
        /// </summary>
        public static string SerializationArrayTypeObjectNotInitialized {
            get {
                return ResourceManager.GetString("SerializationArrayTypeObjectNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly ID: {0}.
        /// </summary>
        public static string SerializationAssemblyId {
            get {
                return ResourceManager.GetString("SerializationAssemblyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly not found: {0}.
        /// </summary>
        public static string SerializationAssemblyNotFound {
            get {
                return ResourceManager.GetString("SerializationAssemblyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary Header Issue: {0} value not mapped.
        /// </summary>
        public static string SerializationBinaryHeader {
            get {
                return ResourceManager.GetString("SerializationBinaryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Boundary Error: {0} - {1}.
        /// </summary>
        public static string SerializationCrossDomainError {
            get {
                return ResourceManager.GetString("SerializationCrossDomainError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Format: {0}.
        /// </summary>
        public static string SerializationInvalidFormat {
            get {
                return ResourceManager.GetString("SerializationInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The serialization map is missing: {0}.
        /// </summary>
        public static string SerializationMap {
            get {
                return ResourceManager.GetString("SerializationMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serialization Member Information: {0}.
        /// </summary>
        public static string SerializationMemberInfo {
            get {
                return ResourceManager.GetString("SerializationMemberInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Member: {0}, {1}, {2}.
        /// </summary>
        public static string SerializationMissingMember {
            get {
                return ResourceManager.GetString("SerializationMissingMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Member Information: {0} {1}.
        /// </summary>
        public static string SerializationNoMemberInfo {
            get {
                return ResourceManager.GetString("SerializationNoMemberInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Object ID: {0}.
        /// </summary>
        public static string SerializationNoObjectID {
            get {
                return ResourceManager.GetString("SerializationNoObjectID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ObjectTypeEnum: {0}.
        /// </summary>
        public static string SerializationObjectTypeEnum {
            get {
                return ResourceManager.GetString("SerializationObjectTypeEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parse Error: {0}.
        /// </summary>
        public static string SerializationParseError {
            get {
                return ResourceManager.GetString("SerializationParseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read beyond EOF.
        /// </summary>
        public static string SerializationReadBeyondEOF {
            get {
                return ResourceManager.GetString("SerializationReadBeyondEOF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This stream has come to pre-mature end..
        /// </summary>
        public static string SerializationStreamEnd {
            get {
                return ResourceManager.GetString("SerializationStreamEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Object Is Missing.
        /// </summary>
        public static string SerializationTopObjectMissing {
            get {
                return ResourceManager.GetString("SerializationTopObjectMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object is not initialized: {0}.
        /// </summary>
        public static string SerializationTopObjectNotInstanciated {
            get {
                return ResourceManager.GetString("SerializationTopObjectNotInstanciated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Code Error: {0}.
        /// </summary>
        public static string SerializationTypeCode {
            get {
                return ResourceManager.GetString("SerializationTypeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type was expected..
        /// </summary>
        public static string SerializationTypeExpected {
            get {
                return ResourceManager.GetString("SerializationTypeExpected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Missing: {0}.
        /// </summary>
        public static string SerializationTypeMissing {
            get {
                return ResourceManager.GetString("SerializationTypeMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Read: {0}.
        /// </summary>
        public static string SerializationTypeRead {
            get {
                return ResourceManager.GetString("SerializationTypeRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type Write: {0}.
        /// </summary>
        public static string SerializationTypeWrite {
            get {
                return ResourceManager.GetString("SerializationTypeWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xml Element Unknown: {0}.
        /// </summary>
        public static string SerializationXmlElement {
            get {
                return ResourceManager.GetString("SerializationXmlElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uri already exists: {0}.
        /// </summary>
        public static string SetObjectUriForMarshal__UriExists {
            get {
                return ResourceManager.GetString("SetObjectUriForMarshal__UriExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The binary stream has been corrupted..
        /// </summary>
        public static string ThBinaryStreamHasBeenCorrupted {
            get {
                return ResourceManager.GetString("ThBinaryStreamHasBeenCorrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &quot;{0}&quot; is not mapped..
        /// </summary>
        public static string TypeIsNotMapped {
            get {
                return ResourceManager.GetString("TypeIsNotMapped", resourceCulture);
            }
        }
    }
}
