// Generated by .NET Reflector from C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App\3.1.6\System.Runtime.Serialization.Formatters.dll

namespace SubSonic.Core.Remoting.Serialization.Binary
{
    using System;
    using System.Runtime.Serialization;

    public sealed class ParseRecord
    {
        public ParseTypeEnum _parseTypeEnum;
        public ObjectTypeEnum _objectTypeEnum;
        public ArrayTypeEnum _arrayTypeEnum;
        public MemberTypeEnum _memberTypeEnum;
        public MemberValueEnum _memberValueEnum;
        public ObjectPositionEnum _objectPositionEnum;
        public string _name;
        public string _value;
        public object _varValue;
        public string _keyDt;
        public Type _dtType;
        public PrimitiveTypeEnum _dtTypeCode;
        public long _objectId;
        public long _idRef;
        public string _arrayElementTypeString;
        public Type _arrayElementType;
        public bool _isArrayVariant;
        public PrimitiveTypeEnum _arrayElementTypeCode;
        public int _rank;
        public int[] _lengthA;
        public int[] _lowerBoundA;
        public int[] _indexMap;
        public int _memberIndex;
        public int _linearlength;
        public int[] _rectangularMap;
        public bool _isLowerBound;
        public ReadObjectInfo _objectInfo;
        public bool _isValueTypeFixup;
        public object _newObj;
        public object[] _objectA;
        public PrimitiveArray _primitiveArray;
        public bool _isRegistered;
        public object[] _memberData;
        public SerializationInfo _si;
        public int _consecutiveNullArrayEntryCount;

        public ParseRecord()
        {
        }

        public void Init()
        {
            _parseTypeEnum = ParseTypeEnum.Empty;
            _objectTypeEnum = ObjectTypeEnum.Empty;
            _arrayTypeEnum = ArrayTypeEnum.Empty;
            _memberTypeEnum = MemberTypeEnum.Empty;
            _memberValueEnum = MemberValueEnum.Empty;
            _objectPositionEnum = ObjectPositionEnum.Empty;
            _name = null;
            _value = null;
            _keyDt = null;
            _dtType = null;
            _dtTypeCode = PrimitiveTypeEnum.Invalid;
            _objectId = 0L;
            _idRef = 0L;
            _arrayElementTypeString = null;
            _arrayElementType = null;
            _isArrayVariant = false;
            _arrayElementTypeCode = PrimitiveTypeEnum.Invalid;
            _rank = 0;
            _lengthA = null;
            _lowerBoundA = null;
            _indexMap = null;
            _memberIndex = 0;
            _linearlength = 0;
            _rectangularMap = null;
            _isLowerBound = false;
            _isValueTypeFixup = false;
            _newObj = null;
            _objectA = null;
            _primitiveArray = null;
            _objectInfo = null;
            _isRegistered = false;
            _memberData = null;
            _si = null;
            _consecutiveNullArrayEntryCount = 0;
        }
    }
}
