// Generated by .NET Reflector from C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App\3.1.6\System.Runtime.Serialization.Formatters.dll

namespace SubSonic.Core.Remoting.Serialization.Binary
{
    using System;
    using System.Runtime.Serialization;

    public sealed class ParseRecord
    {
        public ParseTypeEnum parseTypeEnum;
        public ObjectTypeEnum objectTypeEnum;
        public ArrayTypeEnum arrayTypeEnum;
        public MemberTypeEnum memberTypeEnum;
        public MemberValueEnum memberValueEnum;
        public ObjectPositionEnum objectPositionEnum;
        public string name;
        public string value;
        public object varValue;
        public string keyDt;
        public Type dtType;
        public PrimitiveTypeEnum dtTypeCode;
        public long objectId;
        public long idRef;
        public string arrayElementTypeString;
        public Type arrayElementType;
        public bool isArrayVariant;
        public PrimitiveTypeEnum arrayElementTypeCode;
        public int rank;
        public int[] lengthA;
        public int[] lowerBoundA;
        public int[] indexMap;
        public int memberIndex;
        public int linearlength;
        public int[] rectangularMap;
        public bool isLowerBound;
        public ReadObjectInfo objectInfo;
        public bool isValueTypeFixup;
        public object newObj;
        public object[] objectA;
        public PrimitiveArray primitiveArray;
        public bool isRegistered;
        public object[] memberData;
        public SerializationInfo si;
        public int consecutiveNullArrayEntryCount;

        public ParseRecord()
        {
        }

        public void Init()
        {
            parseTypeEnum = ParseTypeEnum.Empty;
            objectTypeEnum = ObjectTypeEnum.Empty;
            arrayTypeEnum = ArrayTypeEnum.Empty;
            memberTypeEnum = MemberTypeEnum.Empty;
            memberValueEnum = MemberValueEnum.Empty;
            objectPositionEnum = ObjectPositionEnum.Empty;
            name = null;
            value = null;
            keyDt = null;
            dtType = null;
            dtTypeCode = PrimitiveTypeEnum.Invalid;
            objectId = 0L;
            idRef = 0L;
            arrayElementTypeString = null;
            arrayElementType = null;
            isArrayVariant = false;
            arrayElementTypeCode = PrimitiveTypeEnum.Invalid;
            rank = 0;
            lengthA = null;
            lowerBoundA = null;
            indexMap = null;
            memberIndex = 0;
            linearlength = 0;
            rectangularMap = null;
            isLowerBound = false;
            isValueTypeFixup = false;
            newObj = null;
            objectA = null;
            primitiveArray = null;
            objectInfo = null;
            isRegistered = false;
            memberData = null;
            si = null;
            consecutiveNullArrayEntryCount = 0;
        }
    }
}
